branch-defaults:
  main:
    environment: php-socialtweet-local-dev
    group_suffix: null
global:
  application_name: php-socialtweet-local
  branch: null
  default_ec2_keyname: null
  default_platform: PHP 8.3 running on 64bit Amazon Linux 2023
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
